# Amazon Sales Analytics Platform

##  Data Validation

### Project Objective

The objective of this notebook is to perform initial data profiling and validation on the Amazon Sales dataset to understand its structure, identify missing values, detect duplicate records, verify data quality, and prepare the dataset for further analysis and visualization.

---

### Business Problem

Businesses generate large volumes of sales data every day. Before performing any analysis, it is essential to validate the dataset and understand its quality. Poor data quality can lead to inaccurate business insights and incorrect decision-making.

This notebook focuses on examining the dataset, identifying inconsistencies, and ensuring the data is clean and reliable for downstream analytics.

---

### Tools & Technologies

- Python
- Pandas
- NumPy
- Jupyter Notebook

---

### Dataset

**Amazon Sales Dataset**

- Records: 100,000
- Features: 19

## Dataset Preview

In [6]:
import pandas as pd

dataset = pd.read_csv("../Dataset/Amazon_Sales_Data.csv")

dataset.head(10)

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,31-01-2023,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,30-12-2023,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,10-05-2022,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,18-07-2023,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,04-02-2023,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411
5,ORD0000006,31-12-2022,CUST042705,Karan Sharma,P00023,Cookware Set,Books,ReadMore,4,449.73,0.00,215.87,2.74,2017.53,UPI,Delivered,Los Angeles,CA,United States,SELL01494
6,ORD0000007,20-09-2024,CUST037667,Aarav Verma,P00030,Dress Shirt,Clothing,UrbanStyle,2,219.81,0.20,28.14,14.97,394.81,UPI,Delivered,Chicago,IL,Australia,SELL01676
7,ORD0000008,10-11-2022,CUST031165,Rohit Kumar,P00028,Jeans,Toys & Games,KiddoFun,2,306.51,0.05,29.12,6.24,617.73,Debit Card,Pending,Denver,CO,India,SELL00510
8,ORD0000009,26-06-2024,CUST026965,Aman Kapoor,P00031,Kids Toy Car,Sports & Outdoors,Apex,4,146.09,0.00,46.75,7.03,638.14,Debit Card,Delivered,Washington,DC,United States,SELL01895
9,ORD0000010,01-05-2020,CUST029472,Aarav Reddy,P00001,Wireless Earbuds,Clothing,Apex,2,278.21,0.10,60.09,4.88,565.75,Credit Card,Delivered,Houston,TX,United States,SELL01584

## Last Ten Records

In [8]:
dataset.tail(10)

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
99990,ORD0099991,29-05-2024,CUST019886,Sneha Kapoor,P00001,Wireless Earbuds,Electronics,KiddoFun,1,150.64,0.00,7.53,8.38,166.55,Credit Card,Returned,Columbus,OH,United States,SELL01066
99991,ORD0099992,08-05-2021,CUST005627,Kabir Reddy,P00009,Portable SSD 1TB,Toys & Games,HomeEase,2,47.24,0.10,10.20,7.06,102.29,UPI,Cancelled,San Antonio,TX,United States,SELL00444
99992,ORD0099993,17-07-2021,CUST030861,Simran Verma,P00017,Electric Kettle,Toys & Games,Zenith,5,172.38,0.05,0.00,6.44,825.24,UPI,Delivered,Charlotte,NC,United States,SELL01024
99993,ORD0099994,04-05-2023,CUST045239,Mohit Sharma,P00029,T-Shirt,Toys & Games,CoreTech,3,592.56,0.20,113.77,3.82,1539.73,Credit Card,Cancelled,Denver,CO,United States,SELL00855
99994,ORD0099995,09-01-2022,CUST028035,Kabir Kapoor,P00011,Fitness Band,Sports & Outdoors,ReadMore,5,240.94,0.10,54.21,14.66,1153.10,Amazon Pay,Delivered,Seattle,WA,India,SELL01073
99995,ORD0099996,07-03-2023,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,0.00,78.77,2.75,1066.20,UPI,Delivered,Jacksonville,FL,India,SELL00041
99996,ORD0099997,24-11-2021,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,0.00,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449
99997,ORD0099998,29-04-2023,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,0.00,74.37,12.43,1016.40,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028
99998,ORD0099999,01-11-2021,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,0.00,23.52,13.09,330.66,Debit Card,Delivered,Charlotte,NC,United States,SELL00324
99999,ORD0100000,04-12-2021,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,0.05,63.35,3.34,858.52,Debit Card,Delivered,New York,NY,United States,SELL00761

## Dataset Dimensions

In [10]:
dataset.shape

(100000, 20)

## Column Names

In [13]:
dataset.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID',
       'ProductName', 'Category', 'Brand', 'Quantity', 'UnitPrice', 'Discount',
       'Tax', 'ShippingCost', 'TotalAmount', 'PaymentMethod', 'OrderStatus',
       'City', 'State', 'Country', 'SellerID'],
      dtype='object')

## Data Types

In [14]:
dataset.dtypes

OrderID           object
OrderDate         object
CustomerID        object
CustomerName      object
ProductID         object
ProductName       object
Category          object
Brand             object
Quantity           int64
UnitPrice        float64
Discount         float64
Tax              float64
ShippingCost     float64
TotalAmount      float64
PaymentMethod     object
OrderStatus       object
City              object
State             object
Country           object
SellerID          object
dtype: object

## Duplicate Record Analysis

In [15]:
dataset.duplicated().sum()

np.int64(0)

## Missing Value Analysis

In [16]:
dataset.isnull()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

## Missing Value Analysis

In [18]:
dataset.isnull().sum()

OrderID          0
OrderDate        0
CustomerID       0
CustomerName     0
ProductID        0
ProductName      0
Category         0
Brand            0
Quantity         0
UnitPrice        0
Discount         0
Tax              0
ShippingCost     0
TotalAmount      0
PaymentMethod    0
OrderStatus      0
City             0
State            0
Country          0
SellerID         0
dtype: int64

## Statistical Summary

In [24]:
dataset.describe(include="all")

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
count,100000,100000,100000,100000,100000,100000,100000,100000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000,100000,100000,100000,100000,100000
unique,100000,1825,43233,200,50,50,6,10,NaN,NaN,NaN,NaN,NaN,NaN,6,5,20,13,5,1999
top,ORD0099984,28-04-2022,CUST037103,Karan Joshi,P00019,LED Desk Lamp,Electronics,ReadMore,NaN,NaN,NaN,NaN,NaN,NaN,Credit Card,Delivered,Charlotte,TX,United States,SELL01099
freq,1,85,10,556,2098,2098,16853,10204,NaN,NaN,NaN,NaN,NaN,NaN,35038,74628,5110,24896,70058,78
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.001400,302.905748,0.074226,68.468902,7.406660,918.256479,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.413548,171.840797,0.082583,74.131180,4.324057,724.508332,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,5.000000,0.000000,0.000000,0.000000,4.270000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,154.190000,0.000000,15.920000,3.680000,340.890000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,303.070000,0.050000,45.250000,7.300000,714.315000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,451.500000,0.100000,96.060000,11.150000,1349.765000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,599.990000,0.300000,538.460000,15.000000,3534.980000,NaN,NaN,NaN,NaN,NaN,NaN

## Dataset Information

In [23]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   OrderID        100000 non-null  object
 1   OrderDate      100000 non-null  object
 2   CustomerID     100000 non-null  object
 3   CustomerName   100000 non-null  object
 4   ProductID      100000 non-null  object
 5   ProductName    100000 non-null  object
 6   Category       100000 non-null  object
 7   Brand          100000 non-null  object
 8   Quantity       100000 non-null  int64
 9   UnitPrice      100000 non-null  float64
 10  Discount       100000 non-null  float64
 11  Tax            100000 non-null  float64
 12  ShippingCost   100000 non-null  float64
 13  TotalAmount    100000 non-null  float64
 14  PaymentMethod  100000 non-null  object
 15  OrderStatus    100000 non-null  object
 16  City           100000 non-null  object
 17  State          100000 non-null  object
 18  Country        100000 non-null  object
 19  SellerID       100000 non-null  object
dtypes: float64(5), int64(1), object(14)
memory usage: 15.3+ MB

In [29]:
categorical_columns = [
    "Category",
    "Brand",
    "PaymentMethod",
    "OrderStatus",
    "Country",
    "State",
    "City"
]

for column in categorical_columns:
    print("=" * 50)
    print(f"Column: {column}")
    print("-" * 50)
    print(f"Number of Unique Values: {dataset[column].nunique()}")
    print("\nUnique Values:")
    
    for value in dataset[column].unique():
        print(value)
    
    print("=" * 50)
    print()

==================================================
Column: Category
--------------------------------------------------
Number of Unique Values: 6

Unique Values:
Books
Home & Kitchen
Clothing
Toys & Games
Sports & Outdoors
Electronics
==================================================

==================================================
Column: Brand
--------------------------------------------------
Number of Unique Values: 10

Unique Values:
BrightLux
UrbanStyle
Zenith
KiddoFun
ReadMore
Apex
HomeEase
FitLife
CoreTech
NexPro
==================================================

==================================================
Column: PaymentMethod
--------------------------------------------------
Number of Unique Values: 6

Unique Values:
Debit Card
Amazon Pay
Cash on Delivery
Credit Card
UPI
Net Banking
==================================================

==================================================
Column: OrderStatus
--------------------------------------------------
Number of Unique Values: 5

Unique Values:
Delivered
Cancelled
Pending
Shipped
Returned
==================================================

==================================================
Column: Country
--------------------------------------------------
Number of Unique Values: 5

Unique Values:
India
United States
Canada
Australia
United Kingdom
==================================================

==================================================
Column: State
--------------------------------------------------
Number of Unique Values: 13

Unique Values:
DC
TX
NC
CA
IL
CO
FL
NY
WA
IN
PA
AZ
OH
==================================================

==================================================
Column: City
--------------------------------------------------
Number of Unique Values: 20

Unique Values:
Washington
Fort Worth
Austin
Charlotte
San Antonio
Los Angeles
Chicago
Denver
Houston
Jacksonville
New York
Seattle
Indianapolis
Philadelphia
Phoenix
San Diego
Dallas
Columbus
San Francisco
San Jose
==================================================